# Generated by Django 6.0.2 on 2026-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.CharField(max_length=100)),
                ('E_id', models.CharField(max_length=50, unique=True)),
                ('E_address', models.CharField(max_length=100)),
                ('E_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
