# Generated by Django 6.0.2 on 2026-02-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp_details',
            new_name='Emp_detail',
        ),
    ]
